name: JavaCI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: adopt
      - name: Maven Package
        run: mvn -B -U clean package -DskipTests
      - name: Maven Verify
        run: mvn -B -U verify
